### ISSUE TITLE
Just raw instructions to launch your images in Ms Windows environment.

### ISSUE THREAD

**Issue by richhl** [milendyankov/liferay-docker-images#4]
Thx a lot for your work. Going to run a training for Liferay 6.2 and need to launch your image in windows 10 machines. It would be worthwhile to preserve data between training sessions.

I've launched it with:

```
docker run -ti -p 8080:8080 --rm  --name liferay_training azzazzel/liferay-standalone:6.2ga4
```

is it ok? will it preserve data between sessions?

thx in advance.

**Comment by milendyankov** [comment]
This will preserve data for as long as your container is not removed. If you want to preserve the data longer you need to mount an external storage. At the time of creating this (2 years ago) the only option was data-only-container (this is what [liferayctl](https://github.com/milendyankov/liferay-docker-images/blob/master/os-scripts/liferayctl.md) tool uses) or local folders. Since Docker 1.9 you can use [volumes](https://docs.docker.com/engine/admin/volumes/volumes/).
